//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyFeeds.Web.UI.Es.Views.Users {
    
    
    public partial class Login {
        
        /// <summary>
        /// pnlForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::CompanyFeeds.Web.UI.Es.Views.Shared.HtmlContainer pnlForm;
        
        /// <summary>
        /// pnlValidateEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::CompanyFeeds.Web.UI.Es.Views.Shared.HtmlContainer pnlValidateEmail;
    }
}
