<%@ Page Title="" Language="C#" MasterPageFile="~/Views/Shared/Site.Master" AutoEventWireup="true" CodeBehind="Edit.aspx.cs" Inherits="CompanyFeeds.Web.UI.Views.Entries.Edit" %>
<asp:Content runat="server" ContentPlaceHolderID="HeadContent">
	<% PageTitle = Model == null ? "Submit press release" : "Edit press release"; %>
	<script src="/scripts/jquery-ui-1.8.13.core-all.min.js" type="text/javascript"></script>
	<script src="/scripts/jquery.ui.autocomplete.min.js" type="text/javascript"></script>
	<script src="/scripts/resources.js" type="text/javascript"></script>
	<title><%=PageTitle %></title>
	<meta name="description" content="Submit your company press releases for free." />
</asp:Content>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
	<div id="entryEdit">
		<% Html.RenderPartial("EditScripts"); %>
		<h1><%=PageTitle %></h1>
		<div id="fullForm">
			<% Html.BeginForm("Edit", "EntriesController", FormMethod.Post, new {id="entryForm"});%>
			<%= Html.AntiForgeryToken() %>
			<div class="validationErrors">
				<%=Html.ValidationSummary("<h3>Please check the following errors:</h3>", new Dictionary<string, object>
				{
					{"EntryTitle", "Title must not be blank and contain more than 4 characters."}
					,{"CompanyName", "Company must not be blank."}
					,{"Content", "Provide a content."}
					,{"Teaser", Model!=null?"Teaser must not be blank.":""}
					,{"Tag", ""}
				}, null)%>
			</div>
			<div class="item title">
				<label for="EntryTitle">Title</label>
				<%=Html.TextBox("EntryTitle") %>
			</div>
			<div class="item">
				<label for="CompanyName">Company</label>
				<%=Html.TextBox("CompanyName", null, Model!=null?new{disabled="disabled"}:null ) %>
				<%=Html.Hidden("CompanyId") %>
			</div>
			<div class="content">
				<label for="Content">Content</label>
				<%=Html.TextArea("Content") %>
			</div>
			<div class="itemTextarea">
				<label for="Teaser">Teaser</label>
<%				
				if (Model != null || (ModelState["Teaser"] != null && ModelState["Teaser"].Value.RawValue != ""))
				{
%>
					<%=Html.TextArea("Teaser") %>
<%
				}
				else
				{
%>
					<%=Html.TextArea("Teaser", "(autogenerated)", new {disabled="disabled"}) %>
					<span class="enable"><a href="#" onclick="$('#Teaser').prop('disabled',false).focus().val('');$(this).hide();return false;">Add teaser</a></span>
<%
				}
%>
			</div>
			<div class="itemTextarea">
				<label for="ContactInfo" class="optional">Contact info</label>
				<%=Html.TextArea("ContactInfo") %>
			</div>
			<UC:HtmlContainer runat="server" id="pnlAllowComments">
			<p class="note">Determines if users are allowed to post comments on this press release.</p>
			<div class="item check">
				<label for="AllowComments">Allow comments</label>
				<%=Html.CheckBox("AllowComments", Model != null ? Model.AllowComments.GetValueOrDefault(true) : true)%>
			</div>
			</UC:HtmlContainer>
			<br />
			<input type="submit" value="Send &gt;&gt;" class="button" />
				
			<% Html.EndForm();%>
		</div>
	</div>
</asp:Content>
